install:
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force

build: false

test_script:
  - ps: $saResults = Invoke-ScriptAnalyzer -Path .\Set-Window.ps1 -Severity @('Error','Warning') -Recurse -Verbose:$false
  - PS: if ($saResults | Where-Object {$_.Severity -eq 'Error'}) {$saResults | Where-Object {$_.Severity -eq 'Error'} | Format-Table ;Write-Error -Message 'One or more Script Analyzer errors/warnings where found. Build cannot continue!' }
  - ps: if ($saResults | Where-Object {$_.Severity -eq 'Warning'}) {$saResults | Where-Object {$_.Severity -eq 'Warning'} | Format-Table ;Write-Warning -Message 'One or more Script Analyzer warnings where found. Please consider fixing them' }
  - ps: $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  
  
      